VERSION 0.8

FROM maven:3.9.6-eclipse-temurin-17-alpine
WORKDIR /microservices/MicroService2

deps:
  LOCALLY
  SAVE ARTIFACT ../../libs/Lib1 src/libs/Lib1
  SAVE ARTIFACT ../../libs/Lib2 src/libs/Lib2
  SAVE ARTIFACT ../MicroService1 src/microservices/MicroService1
  SAVE ARTIFACT ./ src/microservices/MicroService2
  SAVE ARTIFACT ../pom.xml src/microservices/pom.xml
  SAVE ARTIFACT ../../libs/pom.xml src/libs/pom.xml
  SAVE ARTIFACT ../../pom.xml src/pom.xml

build:
  FROM maven:3.9.6-eclipse-temurin-17-alpine
  COPY --dir +deps/src .
  WORKDIR src
  RUN mvn package -pl microservices/MicroService2 -am
  SAVE ARTIFACT microservices/MicroService2/target/MicroService2-1.0-SNAPSHOT-jar-with-dependencies.jar

docker:
  FROM +build
  CMD ["java", "-jar", "microservices/MicroService2/target/MicroService2-1.0-SNAPSHOT-jar-with-dependencies.jar"]
  SAVE IMAGE microservice2:latest
