VERSION 0.8

build:
  FROM maven:3-eclipse-temurin-17
  COPY ../../libs/Lib1+build/Lib1-1.0-SNAPSHOT.jar .
  RUN mvn install:install-file \
    -Dfile=Lib1-1.0-SNAPSHOT.jar \
    -DgroupId=org.example \
    -DartifactId=Lib1 \
    -Dversion=1.0-SNAPSHOT \
    -Dpackaging=jar
  COPY . .
  RUN mvn package 
  SAVE ARTIFACT microservices/MicroService1/target/MicroService1-1.0-SNAPSHOT-jar-with-dependencies.jar

docker:
  FROM +build
  CMD ["java", "-jar", "target/MicroService1-1.0-SNAPSHOT-jar-with-dependencies.jar"]
  SAVE IMAGE microservice1:latest
